# Generated by Django 6.0.4 on 2026-05-19 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue_system', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='queue_system.organization')),
            ],
        ),
    ]
