# Generated by Django 6.0.4 on 2026-05-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_panel', '0001_initial'),
        ('queue_system', '0006_token_completed_at_token_served_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='queue_system.organization')),
            ],
        ),
    ]
