# Generated by Django 6.0.4 on 2026-05-19 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_panel', '0002_queuereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuereport',
            name='efficiency_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='queuereport',
            name='report_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='queuereport',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
