# Generated by Django 6.0.4 on 2026-05-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_panel', '0004_behaviormonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviormonitoring',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
