# Generated by Django 6.0.4 on 2026-05-19 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='General', max_length=100)),
                ('token_limit', models.IntegerField(default=50, help_text='Maximum tokens per day')),
                ('queue_status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Closed', 'Closed')], default='Active', max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_profile', to='accounts.organizationuser')),
            ],
        ),
        migrations.CreateModel(
            name='QueueBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('queue_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='queue_system.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Serving', 'Serving'), ('Completed', 'Completed'), ('Skipped', 'Skipped')], default='Waiting', max_length=50)),
                ('estimated_time', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to='queue_system.queuebooking')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='queue_system.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueueTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_load', models.IntegerField(default=0)),
                ('waiting_time', models.IntegerField(default=0, help_text='Estimated waiting time in minutes')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='queue_system.organization')),
                ('current_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_tracked', to='queue_system.token')),
            ],
        ),
    ]
