# Generated by Django 6.0.4 on 2026-05-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='work_end',
            field=models.TimeField(blank=True, help_text='Queue closes at (e.g. 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='work_start',
            field=models.TimeField(blank=True, help_text='Queue opens at (e.g. 09:00)', null=True),
        ),
    ]
