# Generated by Django 6.0.4 on 2026-05-19 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0002_organization_work_end_organization_work_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_tokens', models.IntegerField(default=0)),
                ('completed_tokens', models.IntegerField(default=0)),
                ('skipped_tokens', models.IntegerField(default=0)),
                ('peak_hour', models.IntegerField(blank=True, help_text='Hour of the day (0-23) with most bookings', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='queue_system.organization')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
