# Generated by Django 6.0.4 on 2026-05-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
