# Generated by Django 6.0.4 on 2026-05-19 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_and_swap', '0002_emergencyapprovallog'),
        ('queue_system', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_request', to='queue_system.token'),
        ),
    ]
