# Generated by Django 6.0.4 on 2026-05-19 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_and_swap', '0003_alter_emergencyrequest_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotSwapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('swap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='emergency_and_swap.slotswap')),
            ],
        ),
    ]
