# Generated by Django 6.0.4 on 2026-05-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_and_swap', '0004_slotswaplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotswap',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=50),
        ),
    ]
